openapi: 3.0.3
info:
  title: Device Service API
  version: 1.0.0
servers:
  - url: http://localhost/api/devices
paths:
  /:
    get:
      summary: Get all devices
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of devices
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DeviceDTO'

    post:
      summary: Create new device
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceDetailsDTO'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceDetailsDTO'

  /{id}:
    get:
      summary: Get device by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Device details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceDetailsDTO'

    put:
      summary: Update device
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceDetailsDTO'
      responses:
        '200':
          description: Updated device

    delete:
      summary: Delete device
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No content

  /user/{userId}:
    get:
      summary: Get all devices assigned to a user
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Devices list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DeviceDTO'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    DeviceDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        address:
          type: string
        maxConsumption:
          type: number
        userId:
          type: string
          format: uuid

    DeviceDetailsDTO:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        address:
          type: string
        maxConsumption:
          type: number
        userId:
          type: string
          format: uuid
